import { describe, expect, it } from "bun:test";
import { mkdir, mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const pluginRoot = await mkdtemp(join(tmpdir(), "vyline-plugin-manager-test-"));
const dataRoot = await mkdtemp(join(tmpdir(), "vyline-plugin-data-test-"));
process.env.VYLINE_PLUGIN_DIR = pluginRoot;
process.env.VYLINE_DATA_DIR = dataRoot;

const { getPluginStates, listPlugins, withPluginStateLock } = await import("./pluginManager.js");

it("plugin state locks serialize concurrent account writes", async () => {
  const order: string[] = [];
  let release!: () => void;
  const gate = new Promise<void>((resolve) => {
    release = resolve;
  });
  const first = withPluginStateLock("state-lock-test", async () => {
    order.push("first:start");
    await gate;
    order.push("first:end");
  });
  const second = withPluginStateLock("state-lock-test", async () => {
    order.push("second");
  });
  await Bun.sleep(0);
  expect(order).toEqual(["first:start"]);
  release();
  await Promise.all([first, second]);
  expect(order).toEqual(["first:start", "first:end", "second"]);
});

describe("plugin manager manifest compatibility", () => {
  it("loads the manifest.json/main format generated by create-plugin", async () => {
    const pluginDir = join(pluginRoot, "generated-plugin");
    await mkdir(join(pluginDir, "src"), { recursive: true });
    await Bun.write(
      join(pluginDir, "manifest.json"),
      JSON.stringify({
        id: "generated-plugin",
        name: "Generated Plugin",
        version: "0.1.0",
        main: "src/index.ts",
        permissions: ["messages:read"],
      }),
    );
    await Bun.write(join(pluginDir, "src/index.ts"), "export default {};");

    expect(listPlugins()).toContainEqual(
      expect.objectContaining({
        id: "generated-plugin",
        main: "src/index.ts",
        loadable: true,
      }),
    );
  });

  it("rejects unknown permissions and keeps the first duplicate id deterministic", async () => {
    const duplicate = join(pluginRoot, "zzz-duplicate");
    await mkdir(duplicate, { recursive: true });
    await Bun.write(
      join(duplicate, "manifest.json"),
      JSON.stringify({ id: "generated-plugin", name: "Duplicate", version: "1.0.0" }),
    );
    await Bun.write(join(duplicate, "index.ts"), "export default {};\n");

    const unsupported = join(pluginRoot, "unsupported-permission");
    await mkdir(unsupported, { recursive: true });
    await Bun.write(
      join(unsupported, "manifest.json"),
      JSON.stringify({
        id: "unsupported-permission",
        name: "Unsupported",
        version: "1.0.0",
        permissions: ["raw:token"],
      }),
    );
    await Bun.write(join(unsupported, "index.ts"), "export default {};\n");

    const plugins = listPlugins();
    expect(plugins.filter((plugin) => plugin.id === "generated-plugin")).toHaveLength(1);
    expect(plugins.some((plugin) => plugin.id === "unsupported-permission")).toBe(false);
  });

  it("rejects permissions whose runtime capability is not implemented", async () => {
    const unsupported = join(pluginRoot, "send-permission");
    await mkdir(unsupported, { recursive: true });
    await Bun.write(
      join(unsupported, "manifest.json"),
      JSON.stringify({
        id: "send-permission",
        name: "Send Permission",
        version: "1.0.0",
        permissions: ["messages:send"],
      }),
    );
    await Bun.write(join(unsupported, "index.ts"), "export default {};");

    expect(listPlugins().some((plugin) => plugin.id === "send-permission")).toBe(false);
  });

  it("ignores oversized or malformed persisted state without throwing", async () => {
    await Bun.write(join(dataRoot, "plugin-states.json"), `{"broken":${"x".repeat(1_100_000)}}`);
    expect(getPluginStates("broken")).toEqual({});

    await Bun.write(
      join(dataRoot, "plugin-states.json"),
      JSON.stringify({
        valid: { "generated-plugin": true, malformed: "yes" },
        malformed: ["not-an-object"],
      }),
    );
    expect(getPluginStates("valid")).toEqual({ "generated-plugin": true });
    expect(getPluginStates("malformed")).toEqual({});
  });
});
