import { describe, expect, it } from "bun:test";
import { mkdir, mkdtemp, readFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const pluginRoot = await mkdtemp(join(tmpdir(), "vyline-plugin-manager-test-"));
const dataRoot = await mkdtemp(join(tmpdir(), "vyline-plugin-data-test-"));
process.env.VYLINE_PLUGIN_DIR = pluginRoot;
process.env.VYLINE_DATA_DIR = dataRoot;

const { listPlugins, removePluginAccountData } = await import("./pluginManager.js");

describe("plugin manager manifest compatibility", () => {
  it("loads the manifest.json/main format generated by create-plugin", async () => {
    const pluginDir = join(pluginRoot, "generated-plugin");
    await mkdir(join(pluginDir, "src"), { recursive: true });
    await Bun.write(
      join(pluginDir, "manifest.json"),
      JSON.stringify({
        id: "generated-plugin",
        name: "Generated Plugin",
        version: "0.1.0",
        main: "src/index.ts",
        permissions: ["messages:read"],
      }),
    );
    await Bun.write(join(pluginDir, "src/index.ts"), "export default {};");

    expect(listPlugins()).toContainEqual(
      expect.objectContaining({
        id: "generated-plugin",
        main: "src/index.ts",
        loadable: true,
      }),
    );
  });

  it("rejects unknown permissions and keeps the first duplicate id deterministic", async () => {
    const duplicate = join(pluginRoot, "zzz-duplicate");
    await mkdir(duplicate, { recursive: true });
    await Bun.write(
      join(duplicate, "manifest.json"),
      JSON.stringify({ id: "generated-plugin", name: "Duplicate", version: "1.0.0" }),
    );
    await Bun.write(join(duplicate, "index.ts"), "export default {};\n");

    const unsupported = join(pluginRoot, "unsupported-permission");
    await mkdir(unsupported, { recursive: true });
    await Bun.write(
      join(unsupported, "manifest.json"),
      JSON.stringify({
        id: "unsupported-permission",
        name: "Unsupported",
        version: "1.0.0",
        permissions: ["raw:token"],
      }),
    );
    await Bun.write(join(unsupported, "index.ts"), "export default {};\n");

    const plugins = listPlugins();
    expect(plugins.filter((plugin) => plugin.id === "generated-plugin")).toHaveLength(1);
    expect(plugins.some((plugin) => plugin.id === "unsupported-permission")).toBe(false);
  });

  it("rejects malformed and oversized identity fields", async () => {
    const malformed = join(pluginRoot, "malformed-fields");
    await mkdir(malformed, { recursive: true });
    await Bun.write(
      join(malformed, "manifest.json"),
      JSON.stringify({ id: 42, name: "Malformed", version: "1.0.0" }),
    );
    await Bun.write(join(malformed, "index.ts"), "export default {};\n");

    const oversized = join(pluginRoot, "oversized-fields");
    await mkdir(oversized, { recursive: true });
    await Bun.write(
      join(oversized, "manifest.json"),
      JSON.stringify({
        id: "oversized-fields",
        name: "x".repeat(129),
        version: "1.0.0",
      }),
    );
    await Bun.write(join(oversized, "index.ts"), "export default {};\n");

    const plugins = listPlugins();
    expect(plugins.some((plugin) => plugin.dir === "malformed-fields")).toBe(false);
    expect(plugins.some((plugin) => plugin.dir === "oversized-fields")).toBe(false);
  });

  it("removes persisted state and settings for a deleted account", async () => {
    await Bun.write(
      join(dataRoot, "plugin-states.json"),
      JSON.stringify({
        deleted: { "generated-plugin": true },
        retained: { "generated-plugin": true },
      }),
    );
    const settingsRoot = join(dataRoot, "plugin-settings");
    await mkdir(settingsRoot, { recursive: true });
    await Bun.write(join(settingsRoot, "deleted.generated-plugin.json"), "{}\n");
    await Bun.write(join(settingsRoot, "retained.generated-plugin.json"), "{}\n");

    await removePluginAccountData("deleted");

    expect(JSON.parse(await readFile(join(dataRoot, "plugin-states.json"), "utf8"))).toEqual({
      retained: { "generated-plugin": true },
    });
    expect(await readdir(settingsRoot)).toEqual(["retained.generated-plugin.json"]);
  });
});
