import { describe, expect, it } from "bun:test";
import { mkdir, mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

const pluginRoot = await mkdtemp(join(tmpdir(), "vyline-plugin-manager-test-"));
const dataRoot = await mkdtemp(join(tmpdir(), "vyline-plugin-data-test-"));
process.env.VYLINE_PLUGIN_DIR = pluginRoot;
process.env.VYLINE_DATA_DIR = dataRoot;

const { listPlugins } = await import("./pluginManager.js");

describe("plugin manager manifest compatibility", () => {
  it("loads the manifest.json/main format generated by create-plugin", async () => {
    const pluginDir = join(pluginRoot, "generated-plugin");
    await mkdir(join(pluginDir, "src"), { recursive: true });
    await Bun.write(
      join(pluginDir, "manifest.json"),
      JSON.stringify({
        id: "generated-plugin",
        name: "Generated Plugin",
        version: "0.1.0",
        main: "src/index.ts",
        permissions: ["messages:read"],
      }),
    );
    await Bun.write(join(pluginDir, "src/index.ts"), "export default {};");

    expect(listPlugins()).toContainEqual(
      expect.objectContaining({
        id: "generated-plugin",
        main: "src/index.ts",
        loadable: true,
      }),
    );
  });
});
